### ISSUE TITLE
Sample usage

### ISSUE THREAD

**Issue by afnanahmad** [CU-BIC/S3#2]
I was wondering if you've a document with sample usage? Also which API keys are required by this program?

**Comment by fcharih** [comment]
Hi @afnanahmad. Thank you for your question; the software was released to meet a publication deadline, so the documentation is still being developed. @chazingtheinfinite and I are actively working on documenting S3. I suggest that you come back and check for updates within the next couple of days, if you can wait a little.

Cheers,
Francois

**Comment by afnanahmad** [comment]
Hi @fcharih, thats great! We're looking into building something similar, I believe we can extend this software for our system requirements.

I've already figured some of the parameters by looking into the code base and by reading your paper. It would be a great help if you can provide me with a sample Region file and APIs keys file.

Thanks

**Comment by fcharih** [comment]
Are you looking to use the Python or Node version? The implementations are quite different and the inputs are different as well.

**Comment by afnanahmad** [comment]
Currently I’m looking into NodeJS implementation.

**Comment by afnanahmad** [comment]
@fcharih any update on this?

**Comment by fcharih** [comment]
Hi Afnan,

Sorry; it's been a crazy, crazy week/weekend. Barring any unforeseen circumstances, we will have enough documentation to get you started by Friday.

Cheers,
Francois

**Comment by fcharih** [comment]
Hi @afnanahmad. I have added some rudimentary documentation that should help you get started. I am the author of the Node implementation, which I put together really quickly. I am open to adding features if time permits.

Let me know if that helps.

Cheers,
Francois

**Comment by afnanahmad** [comment]
@fcharih thank you for the update and great usage instructions, these are certainly helpful.
